version: '3.3'

services:

  # ---------------------- BACKEND ----------------------
  app:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    volumes:
      - ./:/app
    command: python manage.py runserver 0.0.0.0:5000
    ports:
      - 5000:5000
    env_file:
      - ./docker/.env.dev
    depends_on:
      - postgres
    restart: always

  # ---------------------- DATABASE ----------------------
  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=app
    restart: always

volumes:
  postgres_data:
