version: '3.3'

services:

  # ---------------------- BACKEND ----------------------
  app:
    build: ./
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    environment:
      - ENVIRONMENT=development
      - SECRET_KEY=2ymmbpcv(9@l@8-nc@-@5ldkvgrxv)(+bed^7392-vk%)bj^rj
      - DB_NAME=app
      - DB_USER=jbourdale
      - DB_PASSWORD=password
      - DB_HOST=postgres
      - DB_PORT=5432
      - CLIENT_ID="e18d6952d6854b6c9ab1a161a013e6e3"
      - CLIENT_SECRET="7555b89676e34ac69a1c32c49b3dfef6"
    restart: always

  # ---------------------- DATABASE ----------------------
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=jbourdale
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    restart: always

  # -------------------- CELERY WORKER -------------------
  celery_beat:
    build: ./
    volumes:
      - ./:/app
    command: celery -A new_releases beat -l debug --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - ENVIRONMENT=development
      - SECRET_KEY=2ymmbpcv(9@l@8-nc@-@5ldkvgrxv)(+bed^7392-vk%)bj^rj
      - DB_NAME=app
      - DB_USER=jbourdale
      - DB_PASSWORD=password
      - DB_HOST=postgres
      - DB_PORT=5432
      - CLIENT_ID="e18d6952d6854b6c9ab1a161a013e6e3"
      - CLIENT_SECRET="7555b89676e34ac69a1c32c49b3dfef6"
    restart: always

  celery_worker:
    build: ./
    volumes:
      - ./:/app
    command: celery -A new_releases worker -l debug
    environment:
      - ENVIRONMENT=development
      - SECRET_KEY=2ymmbpcv(9@l@8-nc@-@5ldkvgrxv)(+bed^7392-vk%)bj^rj
      - DB_NAME=app
      - DB_USER=jbourdale
      - DB_PASSWORD=password
      - DB_HOST=postgres
      - DB_PORT=5432
      - CLIENT_ID="e18d6952d6854b6c9ab1a161a013e6e3"
      - CLIENT_SECRET="7555b89676e34ac69a1c32c49b3dfef6"
    restart: always

  # ---------------------- BROKER ----------------------
  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
        - 5672:5672
        - 15672:15672
