# Generated by Django 3.1.1 on 2020-09-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_releases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistRefreshModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date_refresh', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
