# Generated by Django 3.1.1 on 2020-09-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_releases', '0004_auto_20200924_0836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtistRefreshModel',
            new_name='ArtistsRefreshModel',
        ),
    ]
